# Generated by Django 5.2.7 on 2025-10-15 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menucategory",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="users.restaurantprofile",
            ),
        ),
        migrations.AddField(
            model_name="menucategoryimage",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_image",
                to="restaurants.menucategory",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="restaurants.menucategory",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="users.restaurantprofile",
            ),
        ),
        migrations.AddField(
            model_name="menuitemimage",
            name="menu_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="restaurants.menuitem",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotions",
                to="users.restaurantprofile",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="promotions",
            field=models.ManyToManyField(blank=True, to="restaurants.promotion"),
        ),
        migrations.AlterUniqueTogether(
            name="menucategory",
            unique_together={("restaurant", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="menuitem",
            unique_together={("restaurant", "title")},
        ),
    ]
