# Generated by Django 5.2.7 on 2026-04-01 17:19

import restaurants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/promotions/",
                validators=[restaurants.validators.validate_file_size],
            ),
        ),
    ]
