# Generated by Django 5.2.7 on 2025-10-15 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("delivery", "0001_initial"),
        ("orders", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courierearnings",
            name="courier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="earnings",
                to="users.courierprofile",
            ),
        ),
        migrations.AddField(
            model_name="courierearnings",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to="users.courierprofile",
            ),
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_request",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="deliverytracking",
            name="courier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.courierprofile"
            ),
        ),
        migrations.AddField(
            model_name="deliverytracking",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking",
                to="orders.order",
            ),
        ),
    ]
