# Generated by Django 5.2.7 on 2025-10-17 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverytracking",
            options={"ordering": ["-last_updated"]},
        ),
        migrations.RemoveField(
            model_name="deliverytracking",
            name="order",
        ),
        migrations.AddField(
            model_name="deliverytracking",
            name="delivery",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking",
                to="delivery.deliveryrequest",
            ),
            preserve_default=False,
        ),
    ]
