# Generated by Django 5.2.7 on 2025-10-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_alter_deliverytracking_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courierearnings",
            name="commission_rate",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
