# Generated by Django 5.2.7 on 2026-02-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_courierearnings_commission_rate"),
        ("orders", "0008_alter_order_payment_status"),
        ("users", "0006_notificationpreference"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryrequest",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddIndex(
            model_name="deliveryrequest",
            index=models.Index(fields=["status"], name="delivery_de_status_892df4_idx"),
        ),
        migrations.AddIndex(
            model_name="deliveryrequest",
            index=models.Index(
                fields=["assigned_at"], name="delivery_de_assigne_82a158_idx"
            ),
        ),
    ]
