# Generated by Django 5.2.7 on 2025-10-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_restaurantstaffprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("courier", "Courier"),
                    ("restaurant", "Restaurant"),
                    ("restaurant_staff", "Restaurant Staff"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
