# Generated by Django 5.2.7 on 2025-10-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantprofile",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Restaurant profile image",
                null=True,
                upload_to="images/restaurant_images/",
            ),
        ),
    ]
