# Generated by Django 5.2.7 on 2025-11-05 12:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_restaurantprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
