# Generated by Django 5.2.7 on 2026-02-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_notificationpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantprofile",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Restaurant logo",
                null=True,
                upload_to="images/restaurant_logos/",
            ),
        ),
    ]
