# Generated by Django 5.2.7 on 2026-02-06 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_add_logo_to_restaurantprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="new_restaurants",
            field=models.BooleanField(
                default=True,
                help_text="Notifications about new restaurants and menu items",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="promotions_and_offers",
            field=models.BooleanField(
                default=True, help_text="Receive promotional offers and discounts"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="review_reminders",
            field=models.BooleanField(
                default=True, help_text="Reminders to review completed orders"
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
