# Generated by Django 5.2.7 on 2026-02-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_phoneverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(
                blank=True,
                help_text="Google account ID for linked accounts",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
