# Generated by Django 5.2.7 on 2026-04-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0011_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="emailverification",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="phoneverification",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="otp",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="phoneverification",
            name="otp",
            field=models.CharField(max_length=64),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(
                fields=["email", "is_verified"], name="users_email_email_71e869_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(
                fields=["expires_at"], name="users_email_expires_083d9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phoneverification",
            index=models.Index(
                fields=["phone", "is_verified"], name="users_phone_phone_00fbdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="phoneverification",
            index=models.Index(
                fields=["expires_at"], name="users_phone_expires_060708_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone"], name="users_user_phone_9474e8_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_verified"], name="users_user_is_veri_9ce429_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_type", "is_verified"],
                name="users_user_user_ty_fb1442_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["auth_provider"], name="users_user_auth_pr_06709b_idx"
            ),
        ),
    ]
