// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaJNLz-zkj6WvWiaNGzxDjGtopRY-_T40',
    appId: '1:788581837666:android:49a333dc48be12f1321a3b',
    messagingSenderId: '788581837666',
    projectId: 'delivery-1d642',
    storageBucket: 'delivery-1d642.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSf7jkB1XUSmP5svFKjy3hf9kd_La-8ng',
    appId: '1:788581837666:ios:dfcd5e3826056d15321a3b',
    messagingSenderId: '788581837666',
    projectId: 'delivery-1d642',
    storageBucket: 'delivery-1d642.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryCustomerApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ8bDpZpMu1bPy6Hm06ubm3HSRxHs1gkI',
    appId: '1:788581837666:web:245f5c3ac8d25e63321a3b',
    messagingSenderId: '788581837666',
    projectId: 'delivery-1d642',
    authDomain: 'delivery-1d642.firebaseapp.com',
    storageBucket: 'delivery-1d642.firebasestorage.app',
    measurementId: 'G-TYZT8B8YJ3',
  );

}