services:
  db:
    image: imresamu/postgis:16-3.4
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
      - monitoring
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - internal
      - monitoring
    depends_on:
      - redis
      - db

  websocket:
    build: .
    env_file:
      - .env
    command: uv run daphne -b 0.0.0.0 -p 8001 Fudz_api.asgi:application
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    networks:
      - internal
      - monitoring

  redis:
    image: redis:7-alpine
    ports:
      - "6389:6379"
    networks:
      - internal
      - monitoring

  celery:
    build: .
    env_file:
      - .env
    command: uv run celery -A Fudz_api worker --loglevel=info
    volumes:
      - .:/app
    networks:
      - internal
      - monitoring
      
  celery-beat:
    build: .
    env_file:
      - .env
    command: uv run celery -A Fudz_api beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    networks:
      - internal
      - monitoring
    depends_on:
      - redis
      - db

volumes:
  postgres_data:

networks:
  monitoring:
    external: true
