# Generated by Django 5.2.7 on 2025-12-19 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_notification"),
        ("restaurants", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="orderitem",
            name="applied_promotion",
            field=models.ForeignKey(
                blank=True,
                help_text="Promotion applied at time of order",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="restaurants.promotion",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total discount amount for this item",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original menu item price",
                max_digits=10,
                null=True,
            ),
        ),
    ]
